<?php $OnlineUsers = Wo_GetChatUsers('online'); ?>

<div class="wow_content user-status-home wow_home_stories" style="width: 90%; margin-left:auto; margin-right:auto;">
    <div class="wo_page_hdng pag_neg_padd">
        <div class="wo_page_hdng_innr">
            <?php //echo $wo['lang']['stories'] 
            ?>
            Online Friends
        </div>
    </div><?php

        if (!empty($OnlineUsers)) {
        ?>
    <ul class="status-list">
        
            <?php
            foreach ($OnlineUsers as $key => $wo['chatList']) { ?>
                <li>
                    <a class="" onclick="Wo_GetUserMessages(<?php echo $wo['chatList']['user_id']; ?>,'<?php echo $wo['chatList']['name']; ?>');">
                    <img src="<?php echo $wo['chatList']['avatar'];?>" alt="<?php echo $wo['chatList']['avatar'];?> Profile Picture" />
                        <p><?php echo $wo['chatList']['name']; ?></p>
                    </a>
                </li>
        
    </ul>
    <?php }
        }
        else{ ?>
            <div class="text-center">
                No one is available now
            </div>
       <?php }
        
        ?>
</div>