  <!-- CSS File -->
    <link rel="stylesheet" href="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/styles.css" />
    


    <!-- <iframe data-aa="1734720" src="//ad.a-ads.com/1734720?size=200x200" style="width:200px; height:200px; border:0px; padding:0; overflow:hidden; background-color: transparent;" ></iframe> -->
    <!-- Header Starts -->
    <!-- <div class="header">
      <div class="header__left">
        <i id="menu" class="material-icons">menu</i>
        <img
          src="https://www.youtube.com/about/static/svgs/icons/brand-resources/YouTube-logo-full_color_light.svg?cache=72a5d9c"
          alt=""
        />
      </div>

      <div class="header__search">
        <form action="">
          <input type="text" placeholder="Search" />
          <button><i class="material-icons">search</i></button>
        </form>
      </div>

      <div class="header__icons">
        <i class="material-icons display-this">search</i>
        <i class="material-icons">videocam</i>
        <i class="material-icons">apps</i>
        <i class="material-icons">notifications</i>
        <i class="material-icons display-this">account_circle</i>
      </div>
    </div>
    <!-- Header Ends -->

    <!-- Main Body Starts -->
    <!-- <div class="mainBody">
      <!-- Sidebar Starts -->
<!-- 
      <div class="sidebar">
        <div class="sidebar__categories">
          <div class="sidebar__category">
            <i class="material-icons">home</i>
            <span>Home</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">local_fire_department</i>
            <span>Trending</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">subscriptions</i>
            <span>Subcriptions</span>
          </div>
        </div>
        <hr />
        <div class="sidebar__categories">
          <div class="sidebar__category">
            <i class="material-icons">library_add_check</i>
            <span>Library</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">history</i>
            <span>History</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">play_arrow</i>
            <span>Your Videos</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">watch_later</i>
            <span>Watch Later</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">thumb_up</i>
            <span>Liked Videos</span>
          </div>
        </div>
        <hr />
      <!-- </div> --> 
      <!-- Sidebar Ends -->

      <!-- Videos Section -->
      
      <div class="videosRRR">
       
        <div class="videos__containerRRR">
          <!-- Single Video starts -->
          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>
          <!-- Single Video Ends -->

          <!-- Single Video starts -->
          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>
          <!-- Single Video Ends -->

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>

          <div class="videoRRR">
            <div class="video__thumbnail" style="padding: 0%;margin-top: -7%;">
              <video width="300" height="200" controls>
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.mp4" type="video/mp4">
                <source src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/video.ogg" type="video/ogg">
                Your browser does not support the video tag.
              </video>
            </div>
            <div class="video__details" style="padding-top: 10%;">
              <div class="author">
                <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/profile.png" alt="" />
              </div>
              <div class="title">
                <h3>
                  Top 5 Programming Languages to Learn in 2021 | Best Programming Languages to Learn
                </h3>
                <a href="">FutureCoders</a>
                <span>10M Views • 3 Months Ago</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="<?php echo $wo['config']['theme_url'];?>/stylesheet/videos/index.js"></script>
    <!-- Main Body Ends --> 