<link rel="stylesheet" href="<?=$wo['config']['theme_url']?>/layout/store/assets/slick.css">
				<div class="cover-slider">
					<img id="cover-image" src="<?= $wo['page_profile']['cover']?>" alt="<?= $wo['page_profile']['name']?> Cover Image"/>
					<img id="cover-image" src="<?= $wo['page_profile']['cover']?>" alt="<?= $wo['page_profile']['name']?> Cover Image"/>
					<img id="cover-image" src="<?= $wo['page_profile']['cover']?>" alt="<?= $wo['page_profile']['name']?> Cover Image"/>
				</div>
				<script src="<?=$wo['config']['theme_url']?>/layout/store/assets/slick.js"></script>
				<script>
					$(".cover-slider").slick({
						dots: false,
  						infinite: true,
  						speed: 600,
  						slidesToShow: 1,
						autoplay: true,
  						autoplaySpeed: 2000,
						arrows: false,
					});
				</script>