
				<div class="cover-slider">
					<img id="cover-image" src="<?= $wo['store_profile']['cover']?>" alt="<?= $wo['store_profile']['name']?> Cover Image"/>
					<img id="cover-image" src="<?= $wo['store_profile']['cover']?>" alt="<?= $wo['store_profile']['name']?> Cover Image"/>
					<img id="cover-image" src="<?= $wo['store_profile']['cover']?>" alt="<?= $wo['store_profile']['name']?> Cover Image"/>
				</div>				
                