<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M17,14H19V17H22V19H19V22H17V19H14V17H17V14M12.4,5H18V12C15.78,12 13.84,13.21 12.8,15H11L10.6,13H5V20H3V3H12L12.4,5Z"></path></svg></span> Create New Store
					</div>
				</div>
			</div>

			<style>
				.category_checkbox_div{
					background-color: transparent;box-shadow: rgb(60 66 87 / 16%) 0px 0px 0px 1px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 12%) 0px 1px 1px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px;
   					border-radius: 4px;
   					transition: background-color 240ms, box-shadow 240ms;
   					color: #393d4a;
   					font-weight: 400;
   					font-size: 16px;
   					line-height: 28px;
   					padding: 8px;
   					width: 100%;
   					border: 0;
   					outline: 0; padding:5px; min-height: 250px; max-height:250px; overflow:scroll
				}
			</style>
			
            <div class="page-margin wow_content wow_sett_content">
				<form class="create-store-form form-horizontal" method="post" action="<?=$wo['config']['site_url']?>/ro_requests?f=stores&s=create_store">
				<div id="error"></div>
					<div class="wow_form_fields">
						<label for="store_title">Store Name</label>
						<input id="store_title" name="store_title" type="text">
						<span class="help-block">Yore Store Title</span>
					</div>
					<div class="wow_form_fields">
						<label for="owner_name">Owner's Name</label>
						<input id="owner_name" name="owner_name" type="text">
						<span class="help-block">Name of the Owner</span>
					</div>
					<div class="wow_form_fields">
					<label for="country"><?php echo $wo['lang']['country']; ?> </label>
					<select id="country" name="country">
						<?php 
						foreach ($wo['countries_name'] as $country_ids => $country) { 
							$country_id = $wo['setting']['country_id'];
							$selected_contry = ($country_ids == $country_id) ? ' selected' : '' ;
						?>
							<option value="<?php echo $country_ids;?>" <?php echo $selected_contry;?> ><?php echo $country;?></option>
						<?php } ?>
					</select>
				</div>
					<div class="wow_form_fields">
						<label for="store_name">Store URL</label>
						<div class="input-group">
							<span class="input-group-addon"><?php echo $wo['config']['site_url'];?>/store/</span>
							<input id="store_name" name="store_name" type="text">
						</div>
					</div>
					<div class="row">					
					<div class="col-md-6" >
						<label for="store_category" style="font-family: Roboto,sans-serif; font-weight: 500; font-size: 14px; display: block;">Store Category</label>
						<div class="category_checkbox_div">
						<?php //var_dump($wo['store_categories']); ?>
						<?php foreach ($wo['store_categories'] as $key => $category) {?>
								<span><input type="checkbox" class="s_category" name="store_category[<?=$category['id']?>]" id="store_category[<?=$category['id']?>]" value="<?=$category['id']?>"> <label for="store_category[<?=$category['id']?>]"><?=$category['category_name']?></label></span><br>
							<?php } ?>
						</div>
					</div>
					<div class="col-md-6" >
						<label for="store_sub_category" style="font-family: Roboto,sans-serif; font-weight: 500; font-size: 14px; display: block;">Store SubCategory</label>
						<div class="category_checkbox_div" id="store_sub_category">
						<?php foreach ($wo['store_categories'] as $key => $category) {?>
								<div id="cat_<?=$category['id']?>">

								</div>
						<?php } ?>
						
						</div>
					</div>
					</div>
					<div class="wow_form_fields">
						<label for="payment_method">Payment Method</label>
						<select id="payment_method" name="payment_method">						
								<option value="PayPal" >PayPal</option>
								<option value="Bkash" >Bkash</option>
								<option value="Rocket" >Rocket</option>
								<option value="Nagad" >Nagad</option>
								<option value="Paytm" >Paytm</option>						
						</select>
					</div>					
					<div class="wow_form_fields">
						<label for="store_address">Store Address</label>
						<textarea name="store_address" id="store_address" rows="3"></textarea>
						<span class="help-block">Store Address</span>
					</div>
					<div class="wow_form_fields">
						<label for="store_description">Store Description</label>
						<textarea name="store_description" id="store_description" rows="3"></textarea>
						<span class="help-block">Store Description Info</span>
					</div>
					<?php //$fields = Wo_GetCustomFields('page'); 
					//if (!empty($fields)) {
						//foreach ($fields as $key => $wo['field']) {
						//	echo Wo_LoadPage('store/fields');
						//}
					//}
					?>
				  	<div class="app-general-alert setting-update-alert"></div>
					<div class="text-center">
						<a class="btn btn-mat" data-ajax="?link1=stores" href="<?php echo Wo_SeoLink('index.php?link1=stores');?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['create']; ?></button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
   <!-- .row -->
</div>
<!-- .page-margin -->
<script type="text/javascript">

   $(function() {
     $('form.create-store-form').ajaxForm({
       url: <?=$wo['config']['site_url']?> + '/ro_files/ro_requests?f=stores&s=create_store',
       beforeSend: function() {
         $('.create-store-form').find('.add_wow_loader').addClass('btn-loading');
       },
       success: function(data) {
         scrollToTop();
         if (data.status == 200) {
           window.location.href = data.location;
         } else {
             var errors = data.errors+"<br>";
             $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('.create-store-form').find('.add_wow_loader').removeClass('btn-loading');
       }
     });
   });
</script>
<script>
$(".s_category").change(function(){
	var par_id = $(this).attr("id");
	var sub_id = $(this).val();
	if(this.checked) 
    {
		$(this).prop( "disabled", true );
		$.get(Wo_Ajax_Requests_File() + '?f=stores&s=get_subcategory&cat_id='+sub_id, function(data,status){
			if(status=="success"){				
				$.each($.parseJSON(data),function(index,value){
					$("#cat_"+sub_id).append('<input type="checkbox" class="s_subcategory" name="store_subcategory['+value['id']+']" id="store_subcategory['+value['id']+']" value="'+value['id']+'"> <label for="store_subcategory['+value['id']+']">'+value['subcategory_name']+'</label><br>');
				});
				document.getElementById(par_id).disabled=false;
			}				
			
		});		
		
    }
	else{
		$("#cat_"+sub_id).empty();
	}
	
	
});
</script>
<script>
	$("form").submit(function(){
		$.post("<?=$wo['config']['site_url']?>/ro_files/ro_requests.php?f=stores&s=create_store",function(data,status){
			$('.create-store-form').find('.add_wow_loader').addClass('btn-loading');
			scrollToTop();
         if (data.status == 200) {
           window.location.href = data.location;
         } else {
             var errors = data.errors+"<br>";
             $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('.create-store-form').find('.add_wow_loader').removeClass('btn-loading');
		});
	});
</script>