<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists middlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></path></svg></span> Eshops
					</div>
				</div>
			</div>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_menu">
						<!-- <ul class="list-unstyled"> -->
							<!-- <li class="active"><a href="<?php //echo Wo_SeoLink('index.php?link1=store&page1=products'); ?>" data-ajax="?link1=store&page1=products">Products</a></li> -->
							<!-- <li class="active"><a href="<?php //echo Wo_SeoLink('index.php?link1=store'); ?>" data-ajax="?link1=store">Stores</a></li> -->
							<!-- <li><a href="<?php //echo Wo_SeoLink('index.php?link1=suggested-stores'); ?>" data-ajax="?link1=suggested-stores">Suggested</a></li> -->
							<!-- <li><a href="<?php //echo Wo_SeoLink('index.php?link1=liked-stores'); ?>" data-ajax="?link1=liked-stores">Liked</a></li> -->
						<!-- </ul> -->
						<a style="width: 100%;" class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-store');?>" data-ajax="?link1=create-store"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <?php echo $wo['lang']['create'] ?></a>
					</div>
				</div>
			</div>
			<div class="wo_my_pages">
				<div>
					<?php
						$pages = Wo_GetMyPages();
						if (count($pages) > 0) {
							foreach ($pages as $wo['page']) {
								echo Wo_LoadPage('store/pages-list');
							}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></path></svg>No Store Found</div>';
						}
					?>
				<div class="clear"></div>
				</div>
			</div>
		</div>
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>