<?php if ($wo['loggedin'] == true && Wo_IsMobile() == false) { ?>
	<div class="left-sidebar">
		<ul>
			<li class="wow_side_post_fltr">
				<a class="main_menu" href="<?php echo $wo['config']['site_url']; ?>" data-ajax="?index.php?link1=home">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#047cac" d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z"/></svg> <?php echo $wo['lang']['news_feed'];?>
				</a>
				<?php if ($wo['page'] == 'home') { ?>
					<?php if ($wo['config']['order_posts_by'] == 0) { ?>
						<div class="dropdown order_by">
							<svg class="dropdown-toggle" data-toggle="dropdown" role="button" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="currentColor" d="M7,10L12,15L17,10H7Z" opacity="0.7"/></svg>
							<ul class="dropdown-menu dropdown-menu-right" role="button">
								<li class="order_all <?php echo ($wo['user']['order_posts_by'] == 0) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(0);"><?php echo $wo['lang']['all'] ?></a></li>
								<li class="order_people <?php echo ($wo['user']['order_posts_by'] == 1) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(1);"><?php echo $wo['lang']['people_i_follow'] ?></a></li>
							</ul>
						</div>
					<?php } ?>
				<?php } ?>
			</li>
			<li class="wow_side_post_fltr">

				<a class="main_menu" onclick="closeNav()" href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>">
					<img src="<?=$wo['config']['site_url']?>/icons/tag-friend.png" width="25px"> <?php echo $wo['lang']['my_profile'];?>
				</a>

			</li>

			<li class="wow_side_post_fltr">

				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=messages');?>" data-ajax="?link1=messages">
					<img src="<?=$wo['config']['site_url']?>/icons/messenger.png" width="25px"> Chat
				</a>

			</li>

			<li class="wow_side_post_fltr">

				<a class="main_menu" href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f79f58" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></svg> <?php echo $wo['lang']['my_pages'];?>
				</a>

			</li>

			<li class="wow_side_post_fltr">

				<a class="main_menu" href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>" data-ajax="?link1=groups">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#03A9F4" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></svg> <?php echo $wo['lang']['my_groups'];?>
				</a>

			</li>

			<li class="wow_side_post_fltr">
				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby');?>"  data-ajax="?link1=friends-nearby">
					<img src="<?=$wo['config']['site_url']?>/icons/friends.png" width="25px"> People You May Know
				</a>
			</li>

			<li class="wow_side_post_fltr">

				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>">
					<img src="<?=$wo['config']['site_url']?>/icons/blog.png" width="25px"> <?php echo $wo['lang']['blog'] ?>
				</a>


			</li>

			<li class="wow_side_post_fltr">

				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=videos'); ?>">
					<img src="<?=$wo['config']['site_url']?>/icons/movies.png" width="25px"> Videos
				</a>

			</li>

			<li class="wow_side_post_fltr">

				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums">
					<img src="<?=$wo['config']['site_url']?>/icons/gallery.png" width="25px"> <?php echo $wo['lang']['albums'];?>
				</a>
			</li>

			<li>
				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=new-game'); ?>" data-ajax="?link1=new-game">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#03A9F4" d="M16.5,9L13.5,12L16.5,15H22V9M9,16.5V22H15V16.5L12,13.5M7.5,9H2V15H7.5L10.5,12M15,7.5V2H9V7.5L12,10.5L15,7.5Z"></svg> <?php echo $wo['lang']['games'];?>
				</a>
			</li>

			<li>
			<a class="main_menu" href="<?php echo Wo_SeoLink('index.php?link1=jobs'); ?>" data-ajax="?link1=jobs">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4caf50" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></svg> <?php echo $wo['lang']['jobs'];?>
			</a>
		</li>

			<li>
				<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=poke');?>"  data-ajax="?link1=poke">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#009688" d="M21,9A1,1 0 0,1 22,10A1,1 0 0,1 21,11H16.53L16.4,12.21L14.2,17.15C14,17.65 13.47,18 12.86,18H8.5C7.7,18 7,17.27 7,16.5V10C7,9.61 7.16,9.26 7.43,9L11.63,4.1L12.4,4.84C12.6,5.03 12.72,5.29 12.72,5.58L12.69,5.8L11,9H21M2,18V10H5V18H2Z"></svg> <?php echo $wo['lang']['pokes'];?>
				</a>
			</li>

			<li>
				<a class="main_menu" onclick="closeNav()" href="<?php echo $wo['config']['site_url']; ?>/most_liked" data-ajax="?link1=most_liked">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#8d73cc" d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1zm-1-2V4H5v16h14zM7 6h4v4H7V6zm0 6h10v2H7v-2zm0 4h10v2H7v-2zm6-9h4v2h-4V7z"></svg> <?php echo $wo['lang']['popular_posts'];?>
					</a>
				</li>

				<br>
				<p style="color: black;">
					<b><?php 
					$copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
					echo $copy = str_replace('{date}', date('Y'), $copy);
				?></b>

				All Rights Reserved
			</p>
		</ul>
	</div>
<?php } ?>


<?php if ($wo['config']['order_posts_by'] == 0) { ?>
	<script>
		function Wo_StorePosts(type) {
			if (type > 1) {
				return false;
			}
			if (type == 0) {
				$('.order_all').addClass('active');
				$('.order_people').removeClass('active');
			} else {
				$('.order_all').removeClass('active');
				$('.order_people').addClass('active');
			}
			$('#posts-laoded').html('<div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div><div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div>');
			$.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {type:type}, function (data) {
				if (data.status == 200) {
					loadposts();
				}
			});
		}
	</script>
	<?php } ?>