<?php if ($wo['loggedin'] == true && Wo_IsMobile() == false) { ?>
<div class="left-sidebar">
	<ul>
		<li class="wow_side_post_fltr">
			
			<a class="main_menu" onclick="closeNav()" href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>">
      <img src="<?=$wo['config']['site_url']?>/icons/tag-friend.png" width="25px"> <?php echo $wo['lang']['my_profile'];?>
    </a>

		</li>

		<li class="wow_side_post_fltr">

			<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=messages');?>" data-ajax="?link1=messages">
      <img src="<?=$wo['config']['site_url']?>/icons/chat.png" width="25px"> Chat
    </a>

		</li>

		<li class="wow_side_post_fltr">

			<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby');?>"  data-ajax="?link1=friends-nearby">
      <img src="<?=$wo['config']['site_url']?>/icons/friends.png" width="25px"> People You May Know
    </a>
    

		</li>

		<li class="wow_side_post_fltr">

			<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>">
      <img src="<?=$wo['config']['site_url']?>/icons/blog.png" width="25px"> <?php echo $wo['lang']['blog'] ?>
    </a>
    

		</li>

		<li class="wow_side_post_fltr">

			<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums">
      <img src="<?=$wo['config']['site_url']?>/icons/gallery.png" width="25px"> <?php echo $wo['lang']['albums'];?>
    </a>
    

		</li>

		<li class="wow_side_post_fltr">

			<a class="main_menu" onclick="closeNav()" href="<?php echo Wo_SeoLink('index.php?link1=videos'); ?>">
      <img src="<?=$wo['config']['site_url']?>/icons/movies.png" width="25px"> Videos
    </a>

		</li>

		<br>
		<p style="color: black;">
      <b><?php 
      $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
      echo $copy = str_replace('{date}', date('Y'), $copy);
    ?></b>

    All Rights Reserved
  </p>
	</ul>
</div>
<?php } ?>


<?php if ($wo['config']['order_posts_by'] == 0) { ?>
<script>
function Wo_StorePosts(type) {
  if (type > 1) {
     return false;
  }
  if (type == 0) {
	$('.order_all').addClass('active');
	$('.order_people').removeClass('active');
  } else {
	$('.order_all').removeClass('active');
	$('.order_people').addClass('active');
  }
  $('#posts-laoded').html('<div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div><div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div>');
  $.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {type:type}, function (data) {
    if (data.status == 200) {
      loadposts();
    }
  });
}
</script>
<?php } ?>