<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>User</th>
			<th>Platform</th>
			<th>Platform ID</th>
			<th width="30">Action</th>
		</tr>
	</thead>
	<tbody>
		<?php

		global $wo, $sqlConnect;

		$result = mysqli_query($sqlConnect, "Select * from wo_affiliates where status = 0");

		while($row = $result->fetch_assoc()) {

		?>
		<tr>
			<td><?=$row['user_id'];?></td>
			<td><?=$row['platform'];?></td>
			<td><?=$row['platform_id'];?></td>
			<td><a class="btn btn-success">Approve</a><a class="btn btn-danger">Decline</a></td>
		</tr>
		<?php
	}

		?>
	</tbody>


</table>