<div class="container-fluid">
    <div>
        <h3>Manage Banner Advertisements</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Advertisements</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Manage Banner Advertisements</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Manage Banner Advertisements</h6>
                    
                    <form class="manage-banner-ads" method="POST">
                        <div class="form-group form-float row card" style="padding: 10px; background-color:#ccc;" >
                            <div class="form-line col-md-12">
                                <label class="form-label">Banner 1 </label>
                                <textarea name="banner_one" id="banner_one" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('banner_one', true);?></textarea>
                                <small class="admin-info">This is 1st banner ad</small>
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Points 1 </label>
                                <input type="number" name="banner_one_point" id="banner_one_point" class="form-control" value="<?php echo Wo_GetAdPoint('banner_one', true);?>">                                
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Timer 1 </label>
                                <input type="number" name="banner_one_timer" id="banner_one_timer" class="form-control" value="<?php echo Wo_GetAdTimer('banner_one', true);?>">                                
                            </div>
                        </div>
                        <div class="form-group form-float row card" style="padding: 10px; background-color:#ccc;">
                            <div class="form-line col-md-12">
                                <label class="form-label">Banner 2</label>
                                <textarea name="banner_two" id="banner_two" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('banner_two', true);?></textarea>
                                <small class="admin-info">This is 2nd banner ad</small>
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Points 2 </label>
                                <input type="number" name="banner_two_point" id="banner_two_point" class="form-control" value="<?php echo Wo_GetAdPoint('banner_two', true);?>">                                
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Timer 1 </label>
                                <input type="number" name="banner_two_timer" id="banner_two_timer" class="form-control" value="<?php echo Wo_GetAdTimer('banner_two', true);?>">                                
                            </div>
                        </div>
                        <div class="form-group form-float row card" style="padding: 10px; background-color:#ccc;">
                            <div class="form-line col-md-12">
                                <label class="form-label">Banner 3 </label>
                                <textarea name="banner_three" id="banner_three" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('banner_three', true);?></textarea>
                                <small class="admin-info">This is 3rd banner ad</small>
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Points 3 </label>
                                <input type="number" name="banner_three_point" id="banner_three_point" class="form-control" value="<?php echo Wo_GetAdPoint('banner_three', true);?>">                                
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Timer 3 </label>
                                <input type="number" name="banner_three_timer" id="banner_three_timer" class="form-control" value="<?php echo Wo_GetAdTimer('banner_three', true);?>">                                
                            </div>
                        </div>
                        <div class="form-group form-float row card" style="padding: 10px; background-color:#ccc;">
                            <div class="form-line col-md-12">
                                <label class="form-label">Banner 4</label>
                                <textarea name="banner_four" id="banner_four" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('banner_four', true);?></textarea>
                                <small class="admin-info">This is 4th banner ad</small>
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Points 4 </label>
                                <input type="number" name="banner_four_point" id="banner_four_point" class="form-control" value="<?php echo Wo_GetAdPoint('banner_four', true);?>">                                
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Timer 4 </label>
                                <input type="number" name="banner_four_timer" id="banner_four_timer" class="form-control" value="<?php echo Wo_GetAdTimer('banner_four', true);?>">                                
                            </div>
                        </div>
                        <div class="form-group form-float row card" style="padding: 10px; background-color:#ccc;">
                            <div class="form-line col-md-12">
                                <label class="form-label">Banner 5</label>
                                <textarea name="banner_five" id="banner_five" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('banner_five', true);?></textarea>
                                <small class="admin-info">This is 5th banner ad</small>
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Points 5 </label>
                                <input type="number" name="banner_five_point" id="banner_five_point" class="form-control" value="<?php echo Wo_GetAdPoint('banner_five', true);?>">                                
                            </div>
                            <div class="form-line col-md-6">
                                <label class="form-label">Timer 5 </label>
                                <input type="number" name="banner_five_timer" id="banner_five_timer" class="form-control" value="<?php echo Wo_GetAdTimer('banner_five', true);?>">                                
                            </div>
                        </div>                        
                        <div class="manage-banner-ads-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    var form_manage_banner_ads = $('form.manage-banner-ads');
    form_manage_banner_ads.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_banner_ads',
        beforeSend: function() {
            form_manage_banner_ads.find('.waves-effect').text('Please wait..');
        },
        // beforeSubmit : function(arr, $form, options){
        //     for (var i = 0; i < arr.length; i++) {
        //         if (arr[i].name == "banner_one") {
        //             arr[i].value = btoa(unescape(encodeURIComponent($('#banner_one').val())));                    
        //         }
        //         if (arr[i].name == 'banner_three') {
        //             arr[i].value = btoa(unescape(encodeURIComponent($('#banner_three').val())));
        //         }
        //         if (arr[i].name == 'banner_two') {
        //             arr[i].value = btoa(unescape(encodeURIComponent($('#banner_two').val())));
        //         }
        //         if (arr[i].name == 'banner_four') {
        //             arr[i].value = btoa(unescape(encodeURIComponent($('#banner_four').val())));
        //         }
        //         if (arr[i].name == 'banner_five') {
        //             arr[i].value = btoa(unescape(encodeURIComponent($('#banner_five').val())));
        //         }                
        //     }
        //     console.log(arr);
        //   // delete arr[0];
        //   // delete arr[1];
        //   // delete arr[2];
        //   // delete arr[3];
        //   // delete arr[4];
        //   // delete arr[5];
        //   // arr.push({name:'banner_one', value:btoa(unescape(encodeURIComponent($('#banner_one').val())))});
        //   // arr.push({name:'banner_two', value:btoa(unescape(encodeURIComponent($('#banner_two').val())))}); 
        //   // arr.push({name:'banner_three', value:btoa(unescape(encodeURIComponent($('#banner_three').val())))}); 
        //   // arr.push({name:'banner_four', value:btoa(unescape(encodeURIComponent($('#banner_four').val())))}); 
        //   // arr.push({name:'banner_five', value:btoa(unescape(encodeURIComponent($('#banner_five').val())))}); 
        //   // arr.push({name:'post_third', value:btoa(unescape(encodeURIComponent($('#post_third').val())))}); 
        // },
        success: function(data) {
            if (data.status == 200) {
                form_manage_banner_ads.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.manage-banner-ads-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Ads updated successfully</div>');
                setTimeout(function () {
                    $('.manage-banner-ads-alert').empty();
                }, 2000);
            }
        }
    });
});
</script>