<style>
	.div-register{
		background-color: #bbb;
		opacity: 0.4;
	}
</style>
<?php echo Wo_LoadPage('welcome/welcome-header-register');?>
<div class="wrapper">
	<div class="typing-element"></div>
	<div class="login fadeInUp animated animated_5">
		<div class="col-md-6 div-login" style="margin-left: 0; height:100%;">
			<form id="login" class="fadeInUp animated animated_9" method="post" style="margin-top:50%;">
				<p class="title"><?php echo $wo['lang']['login']?></p>
				<div class="errors"></div>
				<div class="wow_form_fields">
					<label for="username"><?php //echo $wo['lang']['username']?>Email or Mobile No.</label>
					<input id="username" name="username" type="text" autocomplete="off" autofocus>
				</div>
				<div class="wow_form_fields">
					<label for="password"><?php echo $wo['lang']['password']?></label>
					<input id="password" name="password" type="password" autocomplete="off">
				</div>
				<div class="forgot_password">
					<a href="<?php echo Wo_SeoLink('index.php?link1=forgot-password');?>"><?php echo $wo['lang']['forget_password']?></a>
				</div>
				<div class="login_signup_combo">
					<div class="login__">
						<button type="submit" class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['login']?></button>
					</div>
					<!-- <div class="signup__">
						<?php //if ($wo['config']['user_registration'] == 1): ?>
						<p><?php //echo $wo['lang']['dont_have_account']?> <a class="dec" href="<?php //echo Wo_SeoLink('index.php?link1=register');?>"><?php //echo $wo['lang']['register']?></a></p>
						<?php //endif ?>
					</div> -->
				</div>
				<?php if(!empty( $_GET['last_url'])){?>
					<div class="form-group"><input type="hidden" name="last_url" value="<?php echo urldecode(Wo_Secure($_GET['last_url']));?>"></div>
				<?php } ?>
				<div class="random_users">
					<?php if ($wo['config']['profile_privacy'] == 1) { ?>
						<hr>
						<?php echo Wo_LoadPage('welcome/welcome-users-profiles');?>
					<?php } ?>
				</div>
			</form>
		</div>
		<div class="col-md-6 div-register" style="margin-left: 0;">
			<form id="register" class="fadeInUp animated animated_9" method="post">
				<p class="title"><?php echo $wo['lang']['sign_up']?></p>
				<div class="errors"></div>
				<?php if ($wo['config']['auto_username'] == 1) { ?>
					<div class="wow_form_fields">
						<label for="first_name"><?php echo $wo['lang']['first_name']?></label>
						<input id="first_name" name="first_name" type="text" autocomplete="off" autofocus>
					</div>
					<div class="wow_form_fields">
						<label for="last_name"><?php echo $wo['lang']['last_name']?></label>
						<input id="last_name" name="last_name" type="text" autocomplete="off" autofocus>
					</div>
				<?php }else{ ?>
					<div class="wow_form_fields">
						<label for="username"><?php echo $wo['lang']['username']?></label>
						<input id="username" name="username" type="text" autocomplete="off" autofocus>
					</div>
				<?php } ?>
				<div class="wow_form_fields">
					<label for="email"><?php echo $wo['lang']['email_address']?></label>
					<input id="email" name="email" type="email" />
				</div>				
				<?php //if($wo['config']['sms_or_email'] == 'sms') {?>
					<div class="wow_form_fields">
						<label for="phone_num_ex"><?php echo $wo['lang']['phone_num_ex']?></label>
						<input id="phone_num_ex" name="phone_num" type="text" />
					</div>
				<?php //} ?>
				<div class="wow_form_fields">
					<label for="password"><?php echo $wo['lang']['password']?></label>
					<input id="password" name="password" type="password" />
					<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
						<ul class="list-unstyled helper-text">
							<li class="length"><?php echo $wo['lang']['least_characters']; ?></li>
							<li class="lowercase"><?php echo $wo['lang']['contain_lowercase']; ?></li>
							<li class="uppercase"><?php echo $wo['lang']['contain_uppercase']; ?></li>
							<li class="special"><?php echo $wo['lang']['number_special']; ?></li>
						</ul>
					<?php } ?>
				</div>
				<div class="wow_form_fields">
					<label for="confirm_password"><?php echo $wo['lang']['confirm_password']?></label>
					<input id="confirm_password" name="confirm_password" type="password" />
				</div>
				<?php 
					if (!empty($fields) && count($fields) > 0) {
						foreach ($fields as $key => $wo['field']) {
							echo Wo_LoadPage('welcome/fields');
						}
					}
				?>
				<div class="wow_form_fields">
					<label for="gender"><?php echo $wo['lang']['gender']?></label>
					<select name="gender" id="gender">
						<option value="0"><?php echo $wo['lang']['gender']?></option>
						<?php foreach ($wo['genders'] as $key => $gender) { ?>
							<option value="<?php echo($key) ?>"><?php echo $gender; ?></option>
						<?php } ?>
					</select>
				</div>
				<?php if($wo['config']['reCaptcha'] == 1) {?>
					<div class="form-group" style="margin-top:10px;">
						<div class="g-recaptcha" data-sitekey="<?php echo $wo['config']['reCaptchaKey']?>"></div>
					</div>
				<?php } ?>
				<?php if(!empty( $_GET['last_url'])){?>
					<div class="form-group">
						<input type="hidden" name="last_url" value="<?php echo urldecode(Wo_Secure($_GET['last_url']));?>">
					</div>
				<?php } ?>
				<div class="terms">
					<input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
					<label for="accept_terms"> 
						<?php echo $wo['lang']['terms_agreement'] ?> <a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'] ?></a> & <a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'] ?></a>
					</label>
					<div class="clear"></div>
				</div>
				<div class="login_signup_combo">
					<div class="login__">
						<button type="submit" class="btn btn-main btn-mat btn-mat-raised add_wow_loader" id="sign_submit" disabled><?php echo $wo['lang']['lets_go']?></button>
					</div>
					<!-- <div class="signup__">
						<p><?php //echo $wo['lang']['already_have_account']?> <a class="dec" href="<?php //echo $wo['config']['site_url'];?>"><?php //echo $wo['lang']['login']?></a></p>
					</div> -->
				</div>
				<?php
				 if (isset($_GET['invite']) && (Wo_IsAdminInvitationExists($_GET['invite']) || Wo_IsUserInvitationExists($_GET['invite']))): ?>
					<input type="text" class="hidden" value="<?php echo $_GET['invite']; ?>" name="invited">
				<?php endif; ?>
			</form>
		</div>
	</div>
</div>
<div class="container"><?php echo Wo_LoadPage('footer/welcome');?></div>

<script>
var working = false;
var $this = $('#login');
var $state = $this.find('.errors');

<?php if($wo['config']['googleLogin'] != 0): ?>
function signOut() {
	var auth2 = gapi.auth2.getAuthInstance();
	auth2.signOut().then(function () {
	  console.log('User signed out.');
	});
}

function onSignIn(googleUser) {
    // The ID token you need to pass to your backend:
    var id_token = googleUser.getAuthResponse().id_token;
    $.post(Wo_Ajax_Requests_File() + '?f=google_login', {id_token: id_token}, function(data, textStatus, xhr) {
    	if (data.status == 200) {
    		signOut();
    		$state.addClass('success');
	        $state.html('<?php echo $wo['lang']['welcome_back'] ?>');
			$this.find('.add_wow_loader').removeClass('btn-loading');
	        setTimeout(function () {
	        	window.location.href = data.location;
	        }, 1000);
    	}
    	else{
			$this.find('button').attr("disabled", false);
			$this.find('.add_wow_loader').removeClass('btn-loading');
	        $state.html(data.message);
    	}
    });
}
<?php endif; ?>

$(function() {
  $('#login').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=login',
    beforeSend: function() {
		working = true;
		$this.find('button').attr("disabled", true);
		$this.find('.add_wow_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
      	$state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_back'] ?>');
		$this.find('.add_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
        	window.location.href = data.location;
        }, 1000);
      } else {
        var errors = data.errors.join("<br>");
		$this.find('button').attr("disabled", false);
		$this.find('.add_wow_loader').removeClass('btn-loading');
        $state.html(errors);
      } 
      working = false;
    }
  });
});
</script>

<script>
var working = false;
var $this = $('#register');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=register',
    beforeSend: function() {
    	<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
    	if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
    		working = true;
			$this.find('button').attr("disabled", true);
			$this.find('.add_wow_loader').addClass('btn-loading');
    	}
    	else{
    		$state.html("<?php echo($wo['lang']['complexity_requirements']) ?>");
    		return false;
    	}
        <?php } else{ ?>
        	working = true;
			$this.find('button').attr("disabled", true);
			$this.find('.add_wow_loader').addClass('btn-loading');
        <?php } ?>

		
    },
    success: function(data) {
      if (data.status == 200) {
		$state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.add_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else if (data.status == 300) {
        window.location.href = data.location;
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.add_wow_loader').removeClass('btn-loading');
        $state.html(data.errors);
      } 
      working = false;
    }
  });
});

function activateButton(element) {
	if(element.checked) {
		document.getElementById("sign_submit").disabled = false;
	}
	else  {
		document.getElementById("sign_submit").disabled = true;
	}
};

<?php if ($wo['config']['password_complexity_system'] == 1) { ?>

(function(){
	var helperText = {
		charLength: document.querySelector('.helper-text .length'),
		lowercase: document.querySelector('.helper-text .lowercase'),
		uppercase: document.querySelector('.helper-text .uppercase'),
		special: document.querySelector('.helper-text .special')
	};
	var password = document.querySelector('#password');
	
	
	
	var pattern = {
		charLength: function() {
			if( password.value.length >= 6 ) {
				return true;
			}
		},
		lowercase: function() {
			var regex = /^(?=.*[a-z]).+$/; // Lowercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		uppercase: function() {
			var regex = /^(?=.*[A-Z]).+$/; // Uppercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		special: function() {
			var regex = /^(?=.*[0-9_\W]).+$/; // Special character or number pattern

			if( regex.test(password.value) ) {
				return true;
			}
		}   
	};
	
	// Listen for keyup action on password field
  password.addEventListener('keyup', function (){
  	    $('.helper-text').slideDown('slow', function() {
  	    	
  	    });
		// Check that password is a minimum of 8 characters
		patternTest( pattern.charLength(), helperText.charLength );
		
		// Check that password contains a lowercase letter		
		patternTest( pattern.lowercase(), helperText.lowercase );
		
		// Check that password contains an uppercase letter
		patternTest( pattern.uppercase(), helperText.uppercase );
		
		// Check that password contains a number or special character
		patternTest( pattern.special(), helperText.special );
    
    // Check that all requirements are fulfilled
    if( hasClass(helperText.charLength, 'valid') &&
			  hasClass(helperText.lowercase, 'valid') && 
			 	hasClass(helperText.uppercase, 'valid') && 
			  hasClass(helperText.special, 'valid')
		) {
			addClass(password.parentElement, 'valid');
    }
    else {
      removeClass(password.parentElement, 'valid');
    }
	});
	
	function patternTest(pattern, response) {
		if(pattern) {
      addClass(response, 'valid');
    }
    else {
      removeClass(response, 'valid');
    }
	}
	
	function addClass(el, className) {
		if (el.classList) {
			el.classList.add(className);
		}
		else {
			el.className += ' ' + className;
		}
	}
	
	function removeClass(el, className) {
		if (el.classList)
				el.classList.remove(className);
			else
				el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
	}
	
	function hasClass(el, className) {
		if (el.classList) {
			console.log(el.classList);
			return el.classList.contains(className);	
		}
		else {
			new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);	
		}
	}
	
})();
<?php } ?>
</script>

<script>
	$('.div-register').mouseover(function(){
	  $(".div-register").css("background-color", "#fff");
	  $(".div-register").css("opacity", "1");
	  $(".div-register").css("transition", "1s");
	  $(".login").css("background-color", "#bbb");
	  $(".div-login").css("opacity", "0.4");
	  $(".login").css("transition", "1s");
	  $(".div-login").css("transition", "1s");
	});

	$('.div-login').mouseover(function(){
	  $(".login").css("background-color", "#fff");
	  $(".div-login").css("opacity", "1");
	  $(".login").css("transition", "1s");
	  $(".div-login").css("transition", "1s");
	  $(".div-register").css("background-color", "#bbb");
	  $(".div-register").css("opacity", "0.4");
	  $(".div-register").css("transition", "1s");
	});
</script>