<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>

	<script src="<?php echo $wo['config']['theme_url'];?>/javascript/jquery-3.1.1.min.js?version=<?php echo $wo['config']['version']; ?>"></script>
      <script src="https://cdn.jsdelivr.net/npm/jquery-ui-touch-punch@0.2.3/jquery.ui.touch-punch.min.js?version=<?php echo $wo['config']['version']; ?>"></script>
	  <script>
        var push_user_id = '';
        var my_id = '<?php echo $wo['user']['web_device_id'] ?>';
        var OneSignal = window.OneSignal || [];
        OneSignal.push(["init", {
          appId: "<?php echo $wo['config']['web_push_id'] ?>",
          autoRegister: true, /* Set to true to automatically prompt visitors */
          notifyButton: {
              enable: true /* Set to false to hide */
          },
          persistNotification: false,
        }]);
       OneSignal.push(function () {
         OneSignal.getUserId(function(userId) {
            push_user_id = userId;
            if (userId != my_id) {
              $.get("<?php echo $wo['config']['site_url'].'/requests.php';?>", {f: 'update_user_device_id', id:push_user_id});
            }
          });
         OneSignal.on('subscriptionChange', function (isSubscribed) {
             if (isSubscribed == false) {
                $.get("<?php echo $wo['config']['site_url'].'/requests.php';?>", {f: 'remove_user_device_id'});
             } else {
                $.get("<?php echo $wo['config']['site_url'].'/requests.php';?>", {f: 'update_user_device_id', id:push_user_id});
             }
         });
       });
      </script>

<script type="text/javascript">
         <?php echo $wo['config']['header_cc']; ?>
         function Wo_Ajax_Requests_File(){
            return "<?php echo $wo['config']['site_url'].'/requests.php';?>"
         }
         <?php if ($wo['config']['smooth_loading'] == 1 && $wo['loggedin'] == true) { ?>
         function Wo_Ajax_Requests_Filee(){
            return "<?php echo $wo['config']['site_url'].'/ajax_loading.php';?>"
         }
         
         var websiteUrl = "<?php echo $wo['config']['site_url'];?>";
         $(function() {
            <?php if ($wo['loggedin'] == true && $wo['config']['find_friends'] == 1) {?>
              <?php if ($wo['user']['last_location_update'] < time()): ?>
                if (navigator.geolocation) {
                  var location = navigator.geolocation.getCurrentPosition(Wo_UpdateLocation);
                }
              <?php endif; ?>
            <?php } ?>
           var box = $('#contnet');
           var ISAPI = $('#ISAPI').val();
           $(document).on('click', 'a[data-ajax]', function(e) {
            if ($('#live_post_id').length > 0) {
                  DeleteLive();
                  window.location = $(this).attr('href');
                  return false;
            }
            Wo_CloseLightbox();
              $('body').removeAttr('no-more-posts');
              if ($('.postText').length) {
                   if ($('.postText').val().length > 0) {
                      if (!confirm("<?php echo html_entity_decode($wo['lang']['havent_finished_post'], ENT_QUOTES)?>")) {
                         return false;
                      } else {
                       $('.postText').val("");
                      }
                   }
               }
               Wo_StartBar();
               window.post = 0;
               var url = $(this).attr('data-ajax');
               e.preventDefault();
               if (!ISAPI) {
                 if (url == '?index.php?link1=home') {
                    $get_value = $('#json-data').val();
                    if ($get_value) {
                        $('#load-more-posts').hide();
                        json_data = JSON.parse($('#json-data').val());
                        if (json_data.page == 'home') {
                            document.getElementById('posts').innerHTML = '<div class="posts_load"><div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div><div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div></div>';
                            loadposts();
                            window.history.pushState({state:'new'},'', websiteUrl);
                            $("html, body").animate({ scrollTop: 0 }, 100);
                            $('.user-details, .pac-container, .lightbox-container').remove();
                            Wo_clearPRecording();
                            Wo_CleanRecordNodes();
                            Wo_stopRecording();
                            Wo_StopLocalStream();
                            
                            return false;
                        }
                    }
                 }
                 $.post(Wo_Ajax_Requests_Filee() + url, {url:url}, function (data) {
                     $('.user-details').remove();
                     json_data = JSON.parse($(data).filter('#json-data').val());
                     if (json_data.welcome_page == 1 || json_data.redirect == 1) {
                         window.location.href = websiteUrl;
                         return false;
                     }
                     if ($('.message-option-btns').length > 0) {
                          if (json_data.url == 'index.php?index.php?link1=home') {
                              window.location.href = websiteUrl;
                          } else {
                             window.location.href = json_data.url;
                          }
                          return false;
                     }
                     //document.getElementById('#contnet').innerHTML = data;
                     box.html(data);
                     if (json_data.is_css_file == 1) {
                       $('.styled-profile').remove();
                       $('footer').append(json_data.css_file);
                       $('.extra-css').html(json_data.css_file_header);
                     } else {
                       $('.styled-profile').attr('href', '');
                       $('.extra-css').empty();
                     }
                     Wo_clearPRecording();
                     Wo_CleanRecordNodes();
                     Wo_stopRecording();
                     Wo_StopLocalStream();
                     if (json_data.page == 'home') {
                       $('.filterby li.filter-by-li').on('click', function (e) {
                         $('.filterby li.filter-by-li').each(function(){
                           $(this).removeClass('avtive');
                           $(this).find('i').addClass('hidden');
                         });
                          $(this).find('i').removeClass('hidden');
                          $(this).addClass('avtive');
                        });
                       window.history.pushState({state:'new'},'', websiteUrl);
                       //window.history.pushState({}, "<?php echo $wo['config']['site_url']?>", websiteUrl);
                     } else {
                       window.history.pushState({state:'new'},'', json_data.url);
                       //window.history.pushState({}, "<?php echo $wo['config']['site_url']?>", json_data.url);
                     }
                     $('.postText').autogrow({vertical: true, horizontal: false, height: 200});
                      window.onpopstate = function(event) {
                        $(window).unbind('popstate');
                        window.location.href = document.location;
                      };

                     if (json_data.page == 'timeline' || json_data.page == 'page' || json_data.page == 'group') {
                       $('.content-container').css('margin-top', '25px');
                       $('.ad-placement-header-footer').find('.contnet').css('margin-top', '20px');
                     } else {
                       $('.content-container').css('margin-top', '45px');
                       $('.ad-placement-header-footer').find('.contnet').css('margin-top', '0');
                     }
                     if (json_data.is_footer == 1 && $('.second-footer').css('display') == 'none') {
                        $('footer .footer-wrapper').show();
                     }
                     else if(json_data.is_footer == 1 && $('.second-footer').css('display') != 'none'){

                     } else {
                      if ($(window).width() < 720) {
                        $('footer .footer-wrapper').show();
                      } else {
                        $('footer .footer-wrapper, .second-footer').hide();
                      }
                     }
                     document.title = decodeHtml(json_data.title);
                     document_title = decodeHtml(json_data.title);
                     $("html, body").animate({ scrollTop: 0 }, 150);
                     Wo_FinishBar();
                     $('#hidden-content').empty();
                     $(document).ready(function() {$('div.leftcol').theiaStickySidebar({additionalMarginTop: 65});});
                     $('#users-reacted-modal').modal("hide");
                 });
                 $('.user-details, .pac-container, .lightbox-container').remove();
               }
           });
       }); 
      <?php } ?>
      function RunLiveAgora(channelName,DIV_ID,token) {
  var agoraAppId = '<?php echo($wo['config']['agora_app_id']) ?>'; 
  var token = token;

  var client = AgoraRTC.createClient({mode: 'live', codec: 'vp8'}); 
  client.init(agoraAppId, function () {


      client.setClientRole('audience', function() {
    }, function(e) {
    });
    
    client.join(token, channelName, <?php echo rand(100,999999); ?>, function(uid) {
    }, function(err) {
    });
    }, function (err) {
    });

    client.on('stream-added', function (evt) {
    var stream = evt.stream;
    var streamId = stream.getId();
    
    client.subscribe(stream, function (err) {
    });
  });
  client.on('stream-subscribed', function (evt) {
    var remoteStream = evt.stream;
    remoteStream.play(DIV_ID);
    $('#player_'+remoteStream.getId()).addClass('embed-responsive-item');
  });
}
      </script>

<script crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>

<script src="<?php echo $wo['config']['theme_url'];?>/javascript/socket.io.js"></script>
  <script>
  let nodejs_system = "<?php echo $wo['config']['node_socket_flow']; ?>";
  let socket = null
  let groupChatListener = {}
  $(()=>{
	<?php if ($wo['config']['node_socket_flow'] == "1"){ $parse = parse_url($wo['config']['site_url']);?>
	var main_hash_id = $('.main_session').val();
	<?php if ($wo['config']['nodejs_ssl'] == "1") {?>
	  socket = io("https://<?php echo $parse['host'];?>:<?php echo $wo['config']['nodejs_ssl_port'];?>/?hash=" + main_hash_id)
	<?php } else {?>
	 socket = io("http://<?php echo $parse['host'];?>:<?php echo $wo['config']['nodejs_port'];?>/?hash=" + main_hash_id)
	<?php } ?>
	let recipient_ids = []
	let recipient_group_ids = []
	setTimeout(function(){ 
	  var inputs = $("input.chat-user-id");
	  $(".chat-wrapper").each(function(){
		let id = $(this).attr("class").substr("chat-wrapper".length);
		let isGroup = $(this).attr("class").substr("chat-wrapper".length).split("_").includes("group")
		if(isGroup) {
		  id = id.substr(' chat_group_'.length)
		  recipient_group_ids.push(id)
		} else{
		  id = id.substr(' chat_'.length)
		  recipient_ids.push(id)
		}
	  });
	  socket.emit('join', {username: "<?php echo $wo['user']['username'];?>", user_id: _getCookie('user_id'), recipient_ids, recipient_group_ids }, ()=>{
		  // setInterval(() => {
		  //   socket.emit("get_user_status", {user_id: _getCookie("user_id")})
		  // }, 2000);
		  setInterval(() => {
			socket.emit("ping_for_lastseen", {user_id: _getCookie("user_id")})
		  }, 2000);
	  });
	 }, 3000);

	socket.on("reconnect", ()=>{
	  let recipient_ids = []
	  let recipient_group_ids = []
	  setTimeout(function(){ 
		var inputs = $("input.chat-user-id");
		$(".chat-wrapper").each(function(){
		  let id = $(this).attr("class").substr("chat-wrapper".length);
		  let isGroup = $(this).attr("class").substr("chat-wrapper".length).split("_").includes("group")
		  if(isGroup) {
			id = id.substr(' chat_group_'.length)
			recipient_group_ids.push(id)
		  } else{
			id = id.substr(' chat_'.length)
			recipient_ids.push(id)
		  }
		});
		socket.emit('join', {username: "<?php echo $wo['user']['username'];?>", user_id: _getCookie('user_id'), recipient_ids, recipient_group_ids }, ()=>{
			setInterval(() => {
			  socket.emit("ping_for_lastseen", {user_id: _getCookie("user_id")})
			}, 2000);
		});
	  }, 3000);
	})
	socket.on("lastseen", (data) => {
		//$('.messages-text[data-message-id='+data.message_id+']').length > 0
		if (data.message_id && data.user_id) {
			  var chat_container = $('.chat-tab').find('#chat_' + data.user_id);
			  if ($('#messageId_'+data.message_id).length > 0) {
					
					if (chat_container.length > 0) {
						  chat_container.find('.message-seen').hide();
						  
					}
					else{
						  $('.message-seen').hide();
					}
					$('#messageId_'+data.message_id).find('.message-seen').hide().html('<i class="fa fa-check"></i> <?php echo $wo["lang"]["seen"];?> (<span class="ajax-time" title="' + data.time + '">' + data.seen + '</span>)').fadeIn(300);
					if (chat_container.length > 0) {
						  //chat_container.find('.online-toggle-hdr').attr('style', '');
						  setTimeout(function(){
							 chat_container.find('.chat-messages-wrapper').scrollTop(chat_container.find('.chat-messages-wrapper')[0].scrollHeight);
						  }, 100);
					}
					else{
					   $(".messages-container").animate({
						   scrollTop: $('.messages-container')[0].scrollHeight
					   }, 200);
					}
			  }
				 
		}
	  })
	 socket.on("register_reaction", (data) => {
		  if(data.status == 200) {
			  $('.post-reactions-icons-m-'+data.id).html(data.reactions);
		  }
	  });
	  socket.on("on_user_loggedin", (data) => {
		$('#chat_' + data.user_id).find('.chat-tab-status').addClass('active');
		$("#online_" + data.user_id).find('svg path').attr('fill', '#60d465');
		$("#messages-recipient-" + data.user_id).find('.dot').css({"background-color": "#63c666"});
	  });
	  socket.on("on_user_loggedoff", (data) => {
		$('#chat_' + data.user_id).find('.chat-tab-status').removeClass('active');
		$("#online_" + data.user_id).find('svg path').attr('fill', '#dddddd');
		$("#messages-recipient-" + data.user_id).find('.dot').css({"background-color": "lightgray"});
	  });
	  socket.on("update_new_posts", (data) => {
		Wo_intervalUpdates(1);
	  });
	  socket.on("on_avatar_changed", (data) => {
		$("#online_" + data.user_id).find('img').attr('src', data.name);
		$("#messages-recipient-" + data.user_id).find('img').attr('src', data.name);
	  });
	  socket.on("on_name_changed", (data) => {
		$("#online_" + data.user_id).find('#chat-tab-id').html(data.name);
		$("#messages-recipient-" + data.user_id).find('.messages-user-name').html(data.name);
	  });
	  socket.on("new_notification", (data) => {
		 <?php if ($wo['config']['nodejs_live_notification'] == "1") {?>
		Wo_GetLastNotification();
		 <?php } ?>
		current_notifications = $('.notification-container').find('.new-update-alert').text();
		$('.notification-container').find('.new-update-alert').removeClass('hidden');
		$('.notification-container').find('.sixteen-font-size').addClass('unread-update');
		$('.notification-container').find('.new-update-alert').text(Number(current_notifications) + 1).show();
		document.getElementById('notification-sound').play();
	  });
	  socket.on("new_notification_removed", (data) => {
		current_notifications = $('.notification-container').find('.new-update-alert').text();
		$('.notification-container').find('.new-update-alert').removeClass('hidden');
		if (Number(current_notifications) > 0) {
		   if ((Number(current_notifications) - 1) == 0) {
			  $('.notification-container').find('.new-update-alert').addClass('hidden');
			  $('.notification-container').find('.new-update-alert').addClass('hidden').text('0').hide();
		   } else {
			  $('.notification-container').find('.sixteen-font-size').addClass('unread-update');
			  $('.notification-container').find('.new-update-alert').text(Number(current_notifications) - 1).show();
		   }
		} else if (Number(current_notifications) == 0) {
		   $('.notification-container').find('.new-update-alert').addClass('hidden');
		   $('.notification-container').find('.new-update-alert').addClass('hidden').text('0').hide();
		} 
	  });

	  socket.on("new_request", (data) => {
		current_requests= $('.requests-container').find('.new-update-alert').text();
		$('.requests-container').find('.new-update-alert').removeClass('hidden');
		$('.requests-container').find('.sixteen-font-size').addClass('unread-update');
		$('.requests-container').find('.new-update-alert').text(Number(current_requests) + 1).show();
		document.getElementById('notification-sound').play();
	  });
	  socket.on("new_request_removed", (data) => {
		current_requests = $('.requests-container').find('.new-update-alert').text();
		$('.requests-container').find('.new-update-alert').removeClass('hidden');
		if (Number(current_requests) > 0) {
		   if ((Number(current_requests) - 1) == 0) {
			  $('.requests-container').find('.new-update-alert').addClass('hidden');
			  $('.requests-container').find('.new-update-alert').addClass('hidden').text('0').hide();
		   } else {
			  $('.requests-container').find('.sixteen-font-size').addClass('unread-update');
			  $('.requests-container').find('.new-update-alert').text(Number(current_requests) - 1).show();
		   }
		} else if (Number(current_requests) == 0) {
		   $('.requests-container').find('.new-update-alert').addClass('hidden');
		   $('.requests-container').find('.new-update-alert').addClass('hidden').text('0').hide();
		} 
	  });

	  socket.on("messages_count", (data) => {
		 current_messages_number = data.count;
		 if (current_messages_number > 0) {
		   $("[data_messsages_count]").text(current_messages_number).removeClass("hidden");
		   $("[data_messsages_count]").attr('data_messsages_count', current_messages_number);
		 } else {
		   $("[data_messsages_count]").text(current_messages_number).addClass("hidden");
		   $("[data_messsages_count]").attr('data_messsages_count', "0");
		 }
	  });
	  socket.on("new_video_call", (data) => {
		 Wo_intervalUpdates(1);
	  });
	  socket.on("load_comment_replies", (data) => {
		 Wo_ViewMoreReplies(data.comment_id);
	  });


	socket.on("color-change", (data)=>{
	  if (data.sender == <?php echo $wo['user']['user_id'];?>) {
		$(".chat_" + data.id).find('.outgoing .message-text, .outgoing .message-media').css('background', data.color);
		$(".chat_" + data.id).find('.outgoing .message-text').css('color', '#fff');
		$(".chat_" + data.id).find('.select-color path').css('fill', data.color);
		$(".chat_" + data.id).find('#color').val(data.color);
	  }
	  let user_id = $('#user-id').val();
	  if(""+user_id === ""+data.id) {
		if(data.sender == <?php echo $wo['user']['user_id']; ?>){
			  $('.send-button').css('background-color', data.color);
			  $('.send-button').css('border-color', data.color);
			  $('#wo_msg_right_prt .message-option-btns .btn svg').css('color', data.color);
			  $(".messages-container").find(".pull-right").find(".message").css('background-color', data.color);
			  $(".messages-container").find(".pull-right").find(".message-text").css('background-color', data.color)
		  }
	  }
	})
	var new_current_messages = 0;
	socket.on("private_message", (data)=>{
	 $('#chat_' + data.sender).find('.online-toggle-hdr').attr('style', 'background: '+data.color+';');
	  var chat_container = $('.chat-tab').find('.chat_main_' + data.id);
	  if (chat_container.length > 0) {
		 chat_container.find('.chat-messages-wrapper').find("div[class*='message-seen']").empty();
		 chat_container.find('.chat-messages-wrapper').find("div[class*='message-typing']").empty();
		 chat_container.find('.chat-messages-wrapper').append(data.messages_html);
		 setTimeout(function(){
			  chat_container.find('.chat-messages-wrapper').scrollTop(chat_container.find('.chat-messages-wrapper')[0].scrollHeight);
		   }, 100);
		 if (data.sender == <?php echo $wo['user']['user_id'];?>) {
		   $(".chat_" + data.id).find('.outgoing .message-text, .outgoing .message-media').css('background', data.color);
		   $(".chat_" + data.id).find('.outgoing .message-text').css('color', '#fff');
		   $(".chat_" + data.id).find('.select-color path').css('fill', data.color);
		   $(".chat_" + data.id).find('#color').val(data.color);
		   $(".text-sender-container .red-list").css('background', data.color);
		   $(".text-sender-container .btn-file").css('background', data.color);
		   $(".text-sender-container .btn-file").css('border-color', data.color);
		 }
	  } else {
		current_number = $('#online_' + data.id).find('.new-message-alert').text();
		$('#online_' + data.id).find('.new-message-alert').html(Number(current_number) + 1).show();

	  }
	  if (!chat_container.find("#sendMessage").is(":focus")) {
		if(data.sender != <?php echo $wo['user']['user_id'];?>){
			document.getElementById('message-sound').play();
		}
	  }
	  if (!chat_container.find('#sendMessage').is(':focus') && chat_container.length == 0) {
		 new_current_messages = new_current_messages + 1;
		 current_messages_number = Number($("[data_messsages_count]").attr('data_messsages_count')) + 1;
		 $("[data_messsages_count]").text(current_messages_number).removeClass("hidden");
		 $("[data_messsages_count]").attr('data_messsages_count', current_messages_number);
		 document.title = 'New Message | ' + document_title;
	  }
	  
	})

	socket.on("group_message", (data)=>{
		  var chat_messages_wrapper = $('.group-messages-wrapper-'+data.id);
		  if (data.status == 200) {
		  if ($(".group-messages-wrapper-"+data.id).find('.no_message').length > 0) {
			$(".group-messages-wrapper-"+data.id).find('.chat-messages').html(data.html);
		  }else{
			$(".group-messages-wrapper-"+data.id).find('.chat-messages').append(data.html);
		  }
		  
		  chat_messages_wrapper.scrollTop(chat_messages_wrapper[0].scrollHeight);
		}
	  })

	<?php
	}
	?>
  });
  </script>

  <!-- JS FILES -->
  <?php if ($wo['config']['reCaptcha'] == 1) { ?>
      <script type="text/javascript" src='https://www.google.com/recaptcha/api.js'></script>
      <?php } ?>
      <?php if ($wo['loggedin'] == false) { ?>
      
      <script type="text/javascript" src="<?php echo $wo['config']['theme_url'];?>/javascript/welcome.js<?php echo $wo['update_cache']; ?>?version=<?php echo $wo['config']['version']; ?>"></script>
      <?php } ?>
      <?php
       if ($wo['config']['node_socket_flow'] == "1") 
       {
         ?>
         <script type="text/javascript">
          const node_socket_flow = "1"
          </script>
      <?php
       }
       if ($wo['config']['node_socket_flow'] == "0") 
       {
         ?>
         <script type="text/javascript">
          const node_socket_flow = "0"
          </script>
      <?php
       }
       ?>
      <script type="text/javascript" src="<?php echo $wo['config']['theme_url'];?>/javascript/script.js<?php echo $wo['update_cache']; ?>?version=<?php echo $wo['config']['version']; ?>"></script>
      <?php if ($wo['loggedin'] == true) {?>
      <?php if ($wo['config']['google_map'] == 1) { ?>
      <script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $wo['config']['google_map_api'];?>&libraries=places"></script>
      <?php } ?>
      <script src="<?php echo $wo['config']['theme_url'];?>/javascript/audioRecord/recorder.js?version=<?php echo $wo['config']['version']; ?>"></script>
      <script src="<?php echo $wo['config']['theme_url'];?>/javascript/audioRecord/record.js?version=<?php echo $wo['config']['version']; ?>"></script>
      <?php } ?>
      <?php if ($wo['page'] == 'timeline' && $wo['loggedin'] == true && $wo['config']['css_upload'] == 1) { ?>
      <?php if (!empty($wo['user_profile']['css_file']) && file_exists($wo['user_profile']['css_file'])) {?>
      <link class="styled-profile" rel="stylesheet" href="<?php echo Wo_GetMedia($wo['user_profile']['css_file']);?>">
      <?php echo $wo['css_file_header'];?>
      <?php } } ?>
      <div class="extra-css"></div>
      <?php if ($wo['page'] != 'welcome') { ?>
      <script>$(document).ready(function() {$('div.leftcol').theiaStickySidebar({additionalMarginTop: 65});});</script>
      <script type="text/javascript">jQuery(document).ready(function() {jQuery('.custom-fixed-element').theiaStickySidebar({additionalMarginTop: 65});});</script>
      <?php }?>
    
      <!-- End 'JS FILES' -->


	<script>
	function Wo_Ajax_Requests_File(){
            return "<?=$wo['config']['site_url']?>/requests.php"
         }
</script>


    <link rel="stylesheet" href="<?php echo $wo['config']['theme_url'];?>/stylesheet/login/style.css" />
    <title><?php echo $wo['title'];?></title>
  </head>
  <body>
    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
		<div class="loginerrors"></div>
          <form id="loginForm" class="sign-in-form" method="post">
            <h2 class="title"><?php echo $wo['lang']['login']?></h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input id="username" name="username" type="text" autocomplete="off" autofocus placeholder="Email or Mobile No." />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input id="password" name="password" type="password" autocomplete="off" placeholder="<?php echo $wo['lang']['password']?>"/>
            </div>
            <input id="loginbtn" type="submit" value="Login" class="btn solid add_wow_loader" />
            <div class="forgot_password">
					<a style="color: #deb7b7 !important;" href="<?php echo Wo_SeoLink('index.php?link1=forgot-password');?>"><?php echo $wo['lang']['forget_password']?></a>
				</div>
          </form>

          <form id="registerForm" class="sign-up-form">
            <h2 class="title"><?php echo $wo['lang']['sign_up']?></h2>
			<div class="registererrors"></div>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input id="first_name" name="first_name" type="text" autocomplete="off" autofocus placeholder="<?php echo $wo['lang']['first_name']?>" />
            </div>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input id="last_name" name="last_name" type="text" autocomplete="off" autofocus placeholder="<?php echo $wo['lang']['last_name']?>" />
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input id="email" name="email" type="email" placeholder="<?php echo $wo['lang']['email_address']?>" />
            </div>
			<div class="input-field">
              <i class="fas fa-mobile"></i>
              <input id="phone_num_ex" name="phone_num" type="text" placeholder="<?php echo $wo['lang']['phone_num_ex']?>" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input  id="rpassword" name="password" type="password" placeholder="<?php echo $wo['lang']['password']?>" />
            </div>
			<div class="input-field">
              <i class="fas fa-lock"></i>
              <input  id="confirm_password" name="confirm_password" type="password" placeholder="<?php echo $wo['lang']['confirm_password']?>" />
            </div>
			<div class="input-field">
			<i class="fas fa-venus-mars"></i>              
					<select name="gender" id="gender" style="background-color: transparent; border:none;"> 
						<option value="0"><?php echo $wo['lang']['gender']?></option>
						<?php foreach ($wo['genders'] as $key => $gender) { ?>
							<option value="<?php echo($key) ?>"><?php echo $gender; ?></option>
						<?php } ?>
					</select>
            </div>
			<?php if($wo['config']['reCaptcha'] == 1) {?>
					<div class="form-group" style="margin-top:10px;">
						<div class="g-recaptcha" data-sitekey="<?php echo $wo['config']['reCaptchaKey']?>"></div>
					</div>
				<?php } ?>
				<?php if(!empty( $_GET['last_url'])){?>
					<div class="form-group">
						<input type="hidden" name="last_url" value="<?php echo urldecode(Wo_Secure($_GET['last_url']));?>">
					</div>
				<?php } ?>
				<div class="terms" style="max-width: 400px;">
					<input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
					<label for="accept_terms"> 
						<?php echo $wo['lang']['terms_agreement'] ?> <a style="color: #deb7b7;" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'] ?></a> & <a style="color: #deb7b7;" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'] ?></a>
					</label>
					<div class="clear"></div>
				</div>

            <input id="registerbtn"  type="submit" class="btn registeradd_wow_loader" value="Sign up" />
			
           
          </form>
        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <h3>New here ?</h3>
            <button class="btn transparent" id="sign-up-btn">
              Sign up
            </button>
          </div>
          <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/login/img/log.svg" class="image" alt="" />
        </div>
        <div class="panel right-panel">
          <div class="content">
            <button class="btn transparent" id="sign-in-btn">
              Sign in
            </button>
          </div>
          <img src="<?php echo $wo['config']['theme_url'];?>/stylesheet/login/img/register.svg" class="image" alt="" />
        </div>
      </div>
    </div>
    
    <script src="<?php echo $wo['config']['theme_url'];?>/stylesheet/login/app.js"></script>
  </body>


  <script>
var working = false;
var $this = $('#loginForm');
var $state = $this.find('.loginerrors');

<?php if($wo['config']['googleLogin'] != 0): ?>
function signOut() {
	var auth2 = gapi.auth2.getAuthInstance();
	auth2.signOut().then(function () {
	  console.log('User signed out.');
	});
}

function onSignIn(googleUser) {
    // The ID token you need to pass to your backend:
    var id_token = googleUser.getAuthResponse().id_token;
    $.post(Wo_Ajax_Requests_File() + '?f=google_login', {id_token: id_token}, function(data, textStatus, xhr) {
    	if (data.status == 200) {
    		signOut();
    		$state.addClass('success');
	        $state.html('<?php echo $wo['lang']['welcome_back'] ?>');
			$this.find('.add_wow_loader').removeClass('btn-loading');
	        setTimeout(function () {
	        	window.location.href = data.location;
	        }, 1000);
    	}
    	else{
			$this.find('#loginbtn').attr("disabled", false);
			$this.find('.add_wow_loader').removeClass('btn-loading');
	        $state.html(data.message);
    	}
    });
}
<?php endif; ?>

$(function() {
  $('#loginForm').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=login',
    beforeSend: function() {
		working = true;
		$this.find('loginbtn').attr("disabled", true);
		$this.find('.add_wow_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
      	$state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_back'] ?>');
		$this.find('.add_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
        	window.location.href = data.location;
        }, 1000);
      } else {
        var errors = data.errors.join("<br>");
		$this.find('#loginbtn').attr("disabled", false);		
        $state.html(errors);
      } 
      working = false;
    }
  });
});
</script>

<script>
var working = false;
var $this = $('#registerForm');
var $state = $this.find('.registererrors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=register',
    beforeSend: function() {
    	<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
    	if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
    		working = true;
			$this.find('#registerbtn').attr("disabled", true);
			$this.find('.registeradd_wow_loader').addClass('btn-loading');
    	}
    	else{
    		$state.html("<?php echo($wo['lang']['complexity_requirements']) ?>");
    		return false;
    	}
        <?php } else{ ?>
        	working = true;
			$this.find('button').attr("disabled", true);
			$this.find('.registeradd_wow_loader').addClass('btn-loading');
        <?php } ?>

		
    },
    success: function(data) {
      if (data.status == 200) {
		$state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.registeradd_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else if (data.status == 300) {
        window.location.href = data.location;
      } else {
        $this.find('registerbtn').attr("disabled", false);
		$this.find('.registeradd_wow_loader').removeClass('btn-loading');
        $state.html(data.errors);
      } 
      working = false;
    }
  });
});

function activateButton(element) {
	if(element.checked) {
		document.getElementById("registerbtn").disabled = false;
	}
	else  {
		document.getElementById("registerbtn").disabled = true;
	}
};

<?php if ($wo['config']['password_complexity_system'] == 1) { ?>

(function(){
	var helperText = {
		charLength: document.querySelector('.helper-text .length'),
		lowercase: document.querySelector('.helper-text .lowercase'),
		uppercase: document.querySelector('.helper-text .uppercase'),
		special: document.querySelector('.helper-text .special')
	};
	var password = document.querySelector('#password');
	
	
	
	var pattern = {
		charLength: function() {
			if( password.value.length >= 6 ) {
				return true;
			}
		},
		lowercase: function() {
			var regex = /^(?=.*[a-z]).+$/; // Lowercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		uppercase: function() {
			var regex = /^(?=.*[A-Z]).+$/; // Uppercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		special: function() {
			var regex = /^(?=.*[0-9_\W]).+$/; // Special character or number pattern

			if( regex.test(password.value) ) {
				return true;
			}
		}   
	};
	
	// Listen for keyup action on password field
  password.addEventListener('keyup', function (){
  	    $('.helper-text').slideDown('slow', function() {
  	    	
  	    });
		// Check that password is a minimum of 8 characters
		patternTest( pattern.charLength(), helperText.charLength );
		
		// Check that password contains a lowercase letter		
		patternTest( pattern.lowercase(), helperText.lowercase );
		
		// Check that password contains an uppercase letter
		patternTest( pattern.uppercase(), helperText.uppercase );
		
		// Check that password contains a number or special character
		patternTest( pattern.special(), helperText.special );
    
    // Check that all requirements are fulfilled
    if( hasClass(helperText.charLength, 'valid') &&
			  hasClass(helperText.lowercase, 'valid') && 
			 	hasClass(helperText.uppercase, 'valid') && 
			  hasClass(helperText.special, 'valid')
		) {
			addClass(password.parentElement, 'valid');
    }
    else {
      removeClass(password.parentElement, 'valid');
    }
	});
	
	function patternTest(pattern, response) {
		if(pattern) {
      addClass(response, 'valid');
    }
    else {
      removeClass(response, 'valid');
    }
	}
	
	function addClass(el, className) {
		if (el.classList) {
			el.classList.add(className);
		}
		else {
			el.className += ' ' + className;
		}
	}
	
	function removeClass(el, className) {
		if (el.classList)
				el.classList.remove(className);
			else
				el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
	}
	
	function hasClass(el, className) {
		if (el.classList) {
			console.log(el.classList);
			return el.classList.contains(className);	
		}
		else {
			new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);	
		}
	}
	
})();
<?php } ?>
</script>


</html>