<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.5/dist/sweetalert2.all.min.js"></script>

<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">

			<h3>Affiliate Form</h3>

			<div >
				<!-- class="page-margin wow_content mt-0" -->
				<form id="affiliateForm" method="post" action="">
				<div class="form-group">
					<label>Promotional Platform: </label>
					<select class="form-control" name="prom_platform" id="prom_platform">
						<option value="Facebook" selected>Facebook</option>
						<option value="Youtube">Youtube</option>
						<option value="Others">Others</option>
					</select>
				</div>
				<div class="form-group">
					<label><span id="pro_id">Facebook</span> ID:</label>
					<input class="form-control" type="text" name="prom_id">
				</div>
				<button class="btn btn-success" type="submit">Submit</button>
			</form>
			</div>
		</div>
		<?php echo Wo_LoadPage('sidebar/content');?>
		
	</div>
</div>

<script type="text/javascript">
var working = false;
var $this = $('#affiliateForm');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=affiliate_form',
    success: function(data) {

    	Swal.fire(
  'Good job!',
  data,
  'success'
)
    	
    }
  });
});
</script>

<script type="text/javascript">

	$( document ).ready(function() {

		$('#prom_platform').on('change', function() {

			$('#pro_id').html(this.value);
  
});

	});

	

	
</script>