<!-- <li data-ad-id="<?php echo $wo['ad']['id']; ?>">
	<div class="aid"><a href="<?php echo $wo['ad']['edit-url']; ?>"><?php echo $wo['ad']['id']; ?></a></div>
	<div class="acomp"><a href="<?php echo $wo['ad']['chart-url']; ?>"><?php echo $wo['ad']['name']; ?></a></div>
	<div class="abid"><?php echo $wo['lang'][$wo['ad']['bidding']]; ?></div>
	<div class="aclck"><a href="<?php echo $wo['ad']['chart-url']; ?>"><?php echo $wo['ad']['clicks']; ?></a></div>
	<div class="avew"><a href="<?php echo $wo['ad']['chart-url']; ?>"><?php echo $wo['ad']['views']; ?></a></div>
	<div class="asts" data-ad-status="<?php echo $wo['ad']['id']; ?>">
		<span class="toggle-user-ad-status pointer" id="<?php echo $wo['ad']['id']; ?>" data-status="<?php echo $wo['ad']['status']; ?>">
		<?php if ($wo['ad']['status'] == 1): ?>
				<span class="wow_ad_sts_actv"><?php echo $wo['lang']['active']; ?></span>
			<?php else: ?>
				<span class="wow_ad_sts_noactv"><?php echo $wo['lang']['not_active']; ?></span>
			<?php endif; ?>
		</span>
	</div>
	<div class="aemp">
		<div class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,16A2,2 0 0,1 14,18A2,2 0 0,1 12,20A2,2 0 0,1 10,18A2,2 0 0,1 12,16M12,10A2,2 0 0,1 14,12A2,2 0 0,1 12,14A2,2 0 0,1 10,12A2,2 0 0,1 12,10M12,4A2,2 0 0,1 14,6A2,2 0 0,1 12,8A2,2 0 0,1 10,6A2,2 0 0,1 12,4Z"></path></svg>
			</a>
			<ul class="dropdown-menu dropdown-menu-right clearfix" role="menu">
				<li>
					<a href="<?php echo $wo['ad']['edit-url']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M2,6V8H14V6H2M2,10V12H14V10H2M20.04,10.13C19.9,10.13 19.76,10.19 19.65,10.3L18.65,11.3L20.7,13.35L21.7,12.35C21.92,12.14 21.92,11.79 21.7,11.58L20.42,10.3C20.31,10.19 20.18,10.13 20.04,10.13M18.07,11.88L12,17.94V20H14.06L20.12,13.93L18.07,11.88M2,14V16H10V14H2Z"></path></svg> <?php echo $wo['lang']['edit_ads']; ?></a>
				</li>
				<li class="delete-ad" id="<?php echo $wo['ad']['id']; ?>">
					<a href="javascript:void(0);"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z"></path></svg> <?php echo $wo['lang']['delete_ad']; ?></a>
				</li>
				<li>
					<a href="<?php echo $wo['ad']['chart-url']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3,14L3.5,14.07L8.07,9.5C7.89,8.85 8.06,8.11 8.59,7.59C9.37,6.8 10.63,6.8 11.41,7.59C11.94,8.11 12.11,8.85 11.93,9.5L14.5,12.07L15,12C15.18,12 15.35,12 15.5,12.07L19.07,8.5C19,8.35 19,8.18 19,8A2,2 0 0,1 21,6A2,2 0 0,1 23,8A2,2 0 0,1 21,10C20.82,10 20.65,10 20.5,9.93L16.93,13.5C17,13.65 17,13.82 17,14A2,2 0 0,1 15,16A2,2 0 0,1 13,14L13.07,13.5L10.5,10.93C10.18,11 9.82,11 9.5,10.93L4.93,15.5L5,16A2,2 0 0,1 3,18A2,2 0 0,1 1,16A2,2 0 0,1 3,14Z"></path></svg> <?php echo $wo['lang']['view_analytics']; ?></a>
				</li>
			</ul>
		</div>
	</div>
</li> -->




<?php if(Wo_GetAd('banner_one', true)!='' && (ro_hasAdsTime('banner_one')|| !ro_hasAds('banner_one'))){?>
<li>
	
		<div class="row bg-danger" style="width: 100%; height:150px;" >        	
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
    				    <a href="<?=$wo['config']['site_url']?>/view-ads/banner_one" class="btn btn-info">Click Here</a>
    				  </div>
    				</div>
  				</div>
				<!-- <a href="<?=$wo['config']['site_url']?>/view-ads/banner_one" class="btn btn-info">Click Here</a> -->
			</div>
        	<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Timer</strong></h3><h4><?php echo Wo_GetAdTimer('banner_one', true);?> Seconds</h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Points</strong></h3><h4><?php echo Wo_GetAdPoint('banner_one', true);?> </h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>			
    	</div> 
	
    
	  
</li>
<?php }?> 
<?php if(Wo_GetAd('banner_two', true)!='' && (ro_hasAdsTime('banner_two')|| !ro_hasAds('banner_two'))){?>
<li class="bg-success">
		<div class="row bg-warning" style="width: 100%; height:150px;" >        	
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
    				    <a href="<?=$wo['config']['site_url']?>/view-ads/banner_two" class="btn btn-info">Click Here</a>
    				  </div>
    				</div>
  				</div>
				<!-- <a href="<?=$wo['config']['site_url']?>/view-ads/banner_two" class="btn btn-info">Click Here</a> -->
			</div>
        	<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Timer</strong></h3><h4><?php echo Wo_GetAdTimer('banner_two', true);?> Seconds</h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Points</strong></h3><h4><?php echo Wo_GetAdPoint('banner_two', true);?> </h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>			
    	</div>
    
</li>
<?php }?>
<?php if(Wo_GetAd('banner_three', true)!='' && (ro_hasAdsTime('banner_three')|| !ro_hasAds('banner_three'))){?>
<li>
		<div class="row bg-info" style="width: 100%; height:150px;" >        	
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
    				    <a href="<?=$wo['config']['site_url']?>/view-ads/banner_three" class="btn btn-info">Click Here</a>
    				  </div>
    				</div>
  				</div>
				<!-- <a href="<?=$wo['config']['site_url']?>/view-ads/banner_three" class="btn btn-info">Click Here</a> -->
			</div>
        	<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Timer</strong></h3><h4><?php echo Wo_GetAdTimer('banner_three', true);?> Seconds</h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Points</strong></h3><h4><?php echo Wo_GetAdPoint('banner_three', true);?> </h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>			
    	</div>
    
</li>
<?php } ?>
<?php if(Wo_GetAd('banner_four', true)!='' && (ro_hasAdsTime('banner_four')|| !ro_hasAds('banner_four'))){?>
<li>
		<div class="row bg-success" style="width: 100%; height:150px;" >        	
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
    				    <a href="<?=$wo['config']['site_url']?>/view-ads/banner_four" class="btn btn-info">Click Here</a>
    				  </div>
    				</div>
  				</div>
				<!-- <a href="<?=$wo['config']['site_url']?>/view-ads/banner_four" class="btn btn-info">Click Here</a> -->
			</div>
        	<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Timer</strong></h3><h4><?php echo Wo_GetAdTimer('banner_four', true);?> Seconds</h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Points</strong></h3><h4><?php echo Wo_GetAdPoint('banner_four', true);?> </h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>			
    	</div>
    
</li>
<?php }?>
<?php if(Wo_GetAd('banner_five', true)!='' && (ro_hasAdsTime('banner_five')|| !ro_hasAds('banner_five'))){?>
<li>
		<div class="row bg-danger" style="width: 100%; height:150px;" >        	
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
    				    <a href="<?=$wo['config']['site_url']?>/view-ads/banner_five" class="btn btn-info">Click Here</a>
    				  </div>
    				</div>
  				</div>
				<!-- <a href="<?=$wo['config']['site_url']?>/view-ads/banner_five" class="btn btn-info">Click Here</a> -->
			</div>
        	<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Timer</strong></h3><h4><?php echo Wo_GetAdTimer('banner_five', true);?> Seconds</h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>
			<div class="col-md-4 text-center" style="height: 100%;">
				<div class="" style="position: relative; height:100%;">
    				<div class="vertical-align-wrap" style="position: absolute;  width: 100%;  height: 100%;   display: table;">
    				  <div class="vertical-align vertical-align--middle" style=" display: table-cell; vertical-align: middle;">
					  	<div style="color:purple; text-align:center;" ><h3><strong>Points</strong></h3><h4><?php echo Wo_GetAdPoint('banner_five', true);?> </h4></div>
    				  </div>
    				</div>
  				</div>			
			</div>			
    	</div>
    
</li>
<?php }?>
