<div class="row">
	<div class="col-md-4 ads_col_4">
		<?php //echo Wo_LoadPage('ads/includes/header'); ?>		
	</div>
	<div class="col-md-8 ads_col_8">
		<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="style.css" />
    <title>Sign in & Sign up Form</title>
  </head>
  <body>
    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          <form action="#" class="sign-in-form">
            <h2 class="title">Sign in</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Username" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" />
            </div>
            <input type="submit" value="Login" class="btn solid" />
            
          </form>
          <form action="#" class="sign-up-form">
            <h2 class="title">Sign up</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="First Name" />
            </div>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Last Name" />
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input type="text" placeholder="Email & Mobile" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" />
            </div>
            <input type="submit" class="btn" value="Sign up" />
           
          </form>
        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <h3>New here ?</h3>
            <button class="btn transparent" id="sign-up-btn">
              Sign up
            </button>
          </div>
          <img src="img/log.svg" class="image" alt="" />
        </div>
        <div class="panel right-panel">
          <div class="content">
            <button class="btn transparent" id="sign-in-btn">
              Sign in
            </button>
          </div>
          <img src="img/register.svg" class="image" alt="" />
        </div>
      </div>
    </div>
    
    <script src="app.js"></script>
  </body>
</html>
 -->
		<div class="ads-cont-wrapper ads-cont-wrapper-home">			
						<?php echo Wo_LoadPage('url_ads/ads');?>					
			
		</div>		
	</div>
</div>
<script>
	
	jQuery(document).ready(function($) {
		$(document).on('click', '.delete-ad', function(event) {
			var self = $(this);	
			$("#delete-ad").attr('data-userad-id',self.attr('id')).modal("show");

		});

		$(document).on('click', '.toggle-user-ad-status', function(event) {
			var self      = $(this);
			var ad_id     = self.attr('id');
			var ad_status = self.attr('data-status');
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'ads',s:'ts',ad_id:ad_id,status:ad_status},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("[data-ad-status='"+ad_id+"']").find('span').text(data.ad);
					if (ad_status == 0) {
						self.html('<span class="wow_ad_sts_actv"><?php echo $wo['lang']['active']; ?></span>');
						self.attr('data-status',1);
					}
					else{
						self.html('<span class="wow_ad_sts_noactv"><?php echo $wo['lang']['not_active']; ?></span>');
						self.attr('data-status',0);
					}
				}
			})
			.fail(function() {
				console.log("error");
			})
		
		});

		$(".load-more-ads").click(function(event) {
			var last_ad = ($("li[data-ad-id]").length > 0) ? $("li[data-ad-id]").last().attr('data-ad-id') : 0;
			var self    = $(this);
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'ads',s:'lm',ad_id:last_ad},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("#user-ads").append(data.html);
				}
				else if(data.status == 404){
					self.removeClass('load-more-ads').html(data.html);
				}
				else{
					self.remove();
				}
			})
			.fail(function() {
				console.log("error");
			})
			
		});
	});

	function Wo_DeleteAd(id){
		if (id && id > 0) {
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'wallet',s:'remove',id:id},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("tr[data-ad-id="+id+"]").slideUp(function(){
						$(this).remove();
					})
					$("#delete-ad").modal("hide");
					location.reload();
				}
			})
			.fail(function() {
				console.log("error");
			})
		}
	}
</script>