<?php 
//$wo['trans'] = Wo_GetMytransactions();
?>
<div class="wo_settings_page wow_content">
	<div class="avatar-holder">
		<img src="<?php echo $wo['setting']['avatar']?>" alt="<?php echo $wo['setting']['name']?> Profile Picture" class="avatar">
		<div class="infoz">
			<h5 title="<?php echo $wo['setting']['name']?>"><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['setting']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>"><?php echo $wo['setting']['name']?></a></h5>
			<p><?php echo $wo['lang']['gifted_points']; ?></p>
		</div>
	</div>
	<hr>

	<div class="earn_points">
		<div class="ep_illus">
		    <div class="ep_how_many wonder_post">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg>
					<b>Points Gifted for Your Good Posts: <?=(ro_totalGiftedPostsPoints($wo['user']['id'])!= 0) ? ro_totalGiftedPostsPoints($wo['user']['id']): 0 ?> Points</b>
				</div>
			<?php //var_dump(ro_giftedPosts()); ?>
		</div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="counter">
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-14.243L7.757 12 12 16.243 16.243 12 12 7.757z"/></svg>
					<p class="point-text"><?php echo $wo['lang']['points']; ?></p>
					<h2 class="timer count-title count-number" data-to="<?= (ro_totalGiftedPoints($wo['user']['id'])!=0) ? ro_totalGiftedPoints($wo['user']['id']) : 0 ;?>" data-speed="1500"><?php echo ro_totalGiftedPoints($wo['user']['id']);?></h2>
					<?php if ($wo['config']['point_allow_withdrawal'] == 1) {?>
						<p class="count-text"><?php echo $wo['config']['dollar_to_point_cost'] . " " . $wo['lang']['points'] . " = $1.00"; ?></p>
					<?php } ?>
				</div>
			</div>
			<div class="col-md-6">
				<div class="points_tip">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
					<?php if ($wo['config']['point_allow_withdrawal'] == 1) { ?>
					<p><?php echo $wo['lang']['earned_points_goto'];?> <a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=payments');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=payments"><?php echo $wo['lang']['my_earnings'];?></a></p>
					<?php } else { ?>
						<p><?php echo $wo['lang']['earned_points_goto'];?> <a href="<?php echo Wo_SeoLink('index.php?link1=wallet'); ?>"><?php echo $wo['lang']['wallet'];?></a></p>
					<?php } ?>
				</div>
			</div>
		</div>
    </div>
</div>